### ISSUE TITLE
Optimization pass epic

### ISSUE THREAD

**Issue by jeaye** [jank-lang/jank#98]
## General
- [ ] Constant propagation
- [ ] Constant folding (compile-time eval of pure expressions with literals)

## Dead code elimination
- [ ] Dead branches
- [ ] Pure statements

## Boxing
- [ ] Arithmetic unboxing for numeric locals
- [ ] Unboxed numeric function parameters (requires either hinting or monomorphization)
- [ ] Unboxing for non-numeric locals (strings, maps, etc -- a la [Project Valhalla](https://en.wikipedia.org/wiki/Project_Valhalla_(Java_language)))
  - If the local is never returned or closed over, it can be on the stack

## Startup
- [ ] Group all fns into a single module to load

## Form rewriting
- [ ] Auto-transient
- [ ] Auto-transducer
- [ ] Zero-cost map destructuring (see [here](https://clojureverse.org/t/do-clojure-still-have-rooms-to-improve-at-compiler-level/7802/20))
- [ ] General loop unrolling
- [ ] Specific loop unrolling (i.e. `get-in`)
- [ ] Faster `str` usage (a la [stringer](https://github.com/kumarshantanu/stringer))

## AOT-only
- [ ] Direct linking (dynamic call)
- [ ] Direct linking (direct call)
- [ ] Unused var removal
- [ ] Flag to elide var meta
- [ ] Remove unused args from fns

## References
* Optimizing compiler: https://en.wikipedia.org/wiki/Optimizing_compiler
* Clojure optimization discussion: https://clojureverse.org/t/do-clojure-still-have-rooms-to-improve-at-compiler-level/7802
* Orbit, optimizing Scheme compiler: https://www.cs.purdue.edu/homes/suresh/502-Fall2008/papers/orbit.pdf
* Lisp compiler optimizations: https://healeycodes.com/lisp-compiler-optimizations

**Comment by frenchy64** [comment]
Idea: if you're likely to call an (immutable) function more than once with a known arity, unbox it until you know its calling convention. If possible, then use `f->call(...)` directly instead of `dynamic_call`. Saves a visit on each call, and the more arguments passed, the more work is saved each call (as `dynamic_call` is more expensive for higher arities).

Not sure if you could go even further and extract the raw function pointers, and also manually pass the context of closures. I'm not sure if that would force you to use `std::function` or if you could call them directly. Would additionally save the virtual method `call`.

Similar things could be done to avoid `apply`. If we know the arities of a function at compile time like `(let [opaque [{} []]] (apply select-keys opaque))` we could skip `apply_to` and compile the equivalent of:
```clojure
(if (= 2 (count opaque))
  (select-keys (nth opaque 0) (nth opaque 1))
  (throw (ex-info "wrong arguments to select-keys" {}))
```

**Comment by jeaye** [comment]
It's impossible to get the type of an unknown object, which could be anything, without a visit. We cannot store that type outside of the visitor. This is more of a physics problem with static type systems and type erasure.

The only way to do this optimization is to know the type ahead of time. Now, once we have seamless interop, and then we add type tracking for known values, we can actually know the full type of a local function and generate a call to `->call` accordingly. This is what we had with C++ codegen and then lost when everything went to LLVM IR. We can get more of it back once we have support for interop, since the compiler and do implicit interop as part of its codegen, not just for explicit interop forms. Until we have that type info ahead of time, though, this is impossible.
